### ISSUE TITLE
直接获取access_token不会有问题吗？

### ISSUE THREAD

**Issue by wuwenbao** [TencentCloudBase/tcb-demo-basic#1]
如果没记错的话获取access_token时会有次数限制。
发现全部的演示案例都是直接掉用，这样很快就会触发限制
这样很容易误导新手

**Comment by lcxfs1991** [comment]
将access_token存放在数据库，到期再更新是会更好，但这里为了简单处理就做直接调用了。但没找到相关次数限制的文档。如果有麻烦贴在这个issue里？

@wuwenbao

**Comment by wuwenbao** [comment]
![image](https://user-images.githubusercontent.com/12627022/52768301-23640400-3068-11e9-96fd-ce74e0c57a3f.png)

**Comment by lcxfs1991** [comment]
@wuwenbao 地址发我一下？

**Comment by wuwenbao** [comment]
@lcxfs1991 每个公众号或者小程序的权限页面都有

**Comment by lcxfs1991** [comment]
好的，这里我优化一下。

**Comment by lcxfs1991** [comment]
@wuwenbao 已经修复，给 wx-js-utils 添加了一个新的接口，配合云开发数据库进行缓存。

https://github.com/lcxfs1991/wx-js-utils/blob/master/docs/WXMINIUser.md
